- name: untar to temporary location
  shell: cd /tmp/ && rm -rf {{webapp_archive_location}}.untarred && mkdir {{webapp_archive_location}}.untarred && cd {{webapp_archive_location}}.untarred && tar xzf {{webapp_archive_location}}
- name: rsync to src dir
  shell: rsync -avP --delete {{webapp_archive_location}}.untarred/ {{src_root}}/
- name: bootstrap
  shell: python {{src_root}}/manage.py bootstrap --app
- name: ensure private config
  shell: python {{src_root}}/manage.py ensure-secret {{deploy_root}}/conf.d/000-private.yml
- name: migrate db
  shell: cd {{src_root}} && python manage.py db upgrade
- name: fix permissions
  shell: chown -R {{user_name}}:{{group_name}} {{deploy_root}}
- name: ensure nginx configuration
  shell: python {{src_root}}/manage.py generate_nginx_config /etc/nginx/sites-enabled/{{app_name}}.conf && nginx -s reload
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: ensure that the conf.d directory exists
  file: dest=/etc/nginx/conf.d state=directory
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Archlinux'
- name: ensure nginx configuration
  shell: python {{src_root}}/manage.py generate_nginx_config /etc/nginx/conf.d/{{app_name}}.conf && nginx -s reload
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Archlinux'

