- name: untar to temporary location
  shell: cd /tmp/ && rm -rf {{webapp_archive_location}}.untarred && mkdir {{webapp_archive_location}}.untarred && cd {{webapp_archive_location}}.untarred && tar xzf {{webapp_archive_location}}
- name: rsync to src dir
  shell: rsync -avP --delete {{webapp_archive_location}}.untarred/ {{src_root}}/
- name: bootstrap
  shell: python {{src_root}}/manage.py bootstrap --app
- name: ensure private config
  shell: python {{src_root}}/manage.py ensure-secret {{deploy_root}}/conf.d/000-private.yml
- name: fix permissions
  shell: chown -R {{user_name}}:{{group_name}} {{deploy_root}}
- name: ensure nginx configuration
  shell: python {{src_root}}/manage.py generate_nginx_config /etc/nginx/sites-enabled/{{app_name}}.conf
  notify: reload nginx config
- name: reload supervisor
  shell: supervisorctl reload
- name: ensure supervisor service
  action: service name=supervisor state=started
- name: try to get local page
  shell: curl http://localhost/
