- name: ensure directories
  action: file state=directory path=$item owner=$user_name group=$group_name
  with_items:
    - $deploy_root
    - $deploy_root/conf.d
  notify: fix permissions and ownerships
- include: nginx.yml
- include: virtualenv.yml
- include: configuration.yml

- name: ensure uwsgi is installed
  shell: $deploy_root/virtualenv/bin/easy_install -U uwsgi creates=$deploy_root/virtualenv/bin/uwsgi
- name: copy source
  copy: src=../src_pkg.tar dest=$webapp_archive_location
  notify: untar sources
- name: configure supervisor
  action: template src=../templates/supervisor.j2 dest=/etc/supervisor/conf.d/$app_name-wsgi.conf
  notify: reload supervisor
