- apt: pkg=nginx state=latest
- name: nginx running
  action: service name=nginx state=started
- name: ensure no nginx default conf
  action: copy dest=/etc/nginx/nginx.conf src=../files/nginx.conf
  notify: reload nginx config
