- apt: pkg=nginx state=latest
- name: nginx running
  action: service name=nginx state=started
- name: ensure no nginx default conf
  action: file path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx config
